version: '3'
services:
  web:
      container_name: web
      build: 
        context: frontend
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
      restart: always
      networks:
        - react-express
      depends_on: 
        - backend
      stdin_open: true

  backend:
    restart: always
    container_name: backend
    build: 
      context: backend
    ports:
      - "5000:5000"
    depends_on:
      - db-sql-server
    networks:
      - express-mssql
      - react-express

  db-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    restart: always
    volumes:
      - ./db-data:/var/lib/mssql/data
    networks:
      - express-mssql

networks:
  react-express:
  express-mssql:

volumes:
  db-data:

    