version: '3'

services:
  db-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-sql-server
    ports:
      - "1455:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    restart: always
    volumes:
      - ./db-data:/var/lib/mssql/data


volumes:
  db-data:
